export enum wsEventEnum {
  OPEN = "OPEN",
  CLOSE = "CLOSE",
  USER_BINDED_TO_CONNECTION = "USER_BINDED_TO_CONNECTION",
  USER_UNBINDED_FROM_CONNECTION = "USER_UNBINDED_FROM_CONNECTION",
  MESSAGE_RECEIVE = "MESSAGE_RECEIVE",
  ERROR = "ERROR",
}
