export enum wsEventEnum {
  OPEN = "OPEN",
  CLOSE = "CLOSE",
  USER_BIND_TO_CONNECTION = "USER_BIND_TO_CONNECTION",
  USER_UNBIND_FROM_CONNECTION = "USER_UNBIND_FROM_CONNECTION",
  MESSAGE_RECEIVE = "MESSAGE_RECEIVE",
  ERROR = "ERROR",
}
