export enum userEventEnum {
  SIGN_IN = "SIGN_IN",
  SIGN_IN_FAIL = "SIGN_IN_FAIL",
  SIGN_OUT = "SIGN_OUT",
  GO_TO_SIGN_IN = "GO_TO_SIGN_IN",
  SET_USER = "SET_USER",
  CLEAR_USER = "CLEAR_USER",
  SET_USER_GROUP = "SET_USER_GROUP",
  CLEAR_USER_GROUP = "CLEAR_USER_GROUP",
}
