export enum userEventEnum {
  LOGIN = "LOGIN",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",
  GO_TO_LOGIN = "GO_TO_LOGIN",
  SET_USER = "SET_USER",
  CLEAR_USER = "CLEAR_USER",
  SET_USER_GROUP = "SET_USER_GROUP",
  CLEAR_USER_GROUP = "CLEAR_USER_GROUP",
}
